### ISSUE TITLE
update bundle editor component to revolve around variables

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang#3830]
[MESDK-249](https://linear.app/opral/issue/MESDK-249/add-bundledeclarations-and-disallow-messagedeclarationstype-===-input) moved declarations to the bundle level and simplified the mental model to revolve around variables.

### Task

- [X] change naming from `input` to `variables`
- [ ] allow users to create new input and local variables
- [ ] adding a new selector chooses from a variable
- [ ] allow editing an existing variable

![CleanShot 2024-09-20 at 22.54.23@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/bf16b3e4-f768-462a-aad5-bcea2e2ec469/bc834854-bff2-423f-90f5-e18a2be35e4e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iZjE2YjNlNC1mNzY4LTQ2MmEtYWFkNS1iY2VhMmUyZWM0NjkvYmM4MzQ4NTQtYmZmMi00MjNmLTkwZjUtZTE4YTJiZTM1ZTRlIiwiaWF0IjoxNzI2ODg3NTEzLCJleHAiOjMzMjk3NDQ3NTEzfQ.JzdSdSUDJhaXCReMpd4Yc-k9PZdOFDvk2izGnRSlVTw "=3060x")

- [ ] change `ref` to `base` for unified communcation

The new vocabulary is `baseLocale` and not source or ref language tag anymore.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/0d7c30a4-c818-42a8-a9a2-f225500a01d5/0110e32d-63c4-47b3-a032-f57734c18795?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wZDdjMzBhNC1jODE4LTQyYTgtYTlhMi1mMjI1NTAwYTAxZDUvMDExMGUzMmQtNjNjNC00N2IzLWEwMzItZjU3NzM0YzE4Nzk1IiwiaWF0IjoxNzI3MTE4NjEwLCJleHAiOjMzMjk3Njc4NjEwfQ.kjlj39I9AUkMSJcd_kyN92OT50FLUxcxAnI77PgoEEA " alt="CleanShot 2024-09-23 at 15.09.09@2x.png" width="974" height="388" />
