### ISSUE TITLE
introduce markup placeholders 

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang#840]
## Problem

Users can not use markup placeholders. 

_From https://discord.com/channels/897438559458430986/1110687789395226716/1110903944143712338_: 

<img width="845" alt="CleanShot 2023-05-24 at 14 27 55@2x" src="https://github.com/inlang/inlang/assets/35429197/f17e0d14-a761-4680-afff-fd7c52f3f41c">

## Proposal

Add markup placeholders.

_From the message format working group https://github.com/unicode-org/message-format-wg/blob/main/spec/syntax.md#markup-elements_

<img width="1064" alt="CleanShot 2023-05-24 at 14 25 16@2x" src="https://github.com/inlang/inlang/assets/35429197/76e6b6cb-9888-43e0-a743-f70ad7282ba9">

## Sub-issues

- [ ] add markup placeholders to the AST (core)
- [ ] add markup placeholder support to the SDK-JS (sdk-js)
- [ ] add markup placeholder support to the editor (editor)

## Additional information

- The Fluent spec doesn't seem to contain Markup placeholders, see https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf.
